# Generated by Django 6.1 on 2026-08-21 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'title'], name='catalog_cou_is_acti_d7f8f8_idx'),
        ),
    ]
